"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "../lib/supabase-browser";
import { BackOffice, GiftRecord, TransferRequest } from "./back-office";
import "./administration.css";

type Tab = "gifts" | "members" | "accounts" | "settings";
type Member = { id:string; name:string; email?:string|null; role:string; access_status:string; is_active:boolean; auth_user_id?:string|null; auth?:{emailConfirmedAt?:string|null;lastSignInAt?:string|null;createdAt?:string;providers?:string[]}|null };
type Account = { id:string; member_id:string; name:string; account_type:string; institution?:string|null; currency:string; account_number_last4?:string|null; wallet_address?:string|null; network?:string|null };
type Holding = { id:string; account_id:string; asset_type:string; symbol?:string|null; isin?:string|null; name:string; quantity:number; average_cost?:number|null; currency:string; exchange?:string|null; last_price?:number|null; last_price_at?:string|null };
type MarketResult = { symbol:string; name:string; type:string; region:string; currency:string };

async function headers() {
  const session = (await supabaseBrowser.auth.getSession()).data.session;
  return { authorization: "Bearer " + (session?.access_token || ""), "content-type": "application/json" };
}
async function api(url:string, init:RequestInit = {}) {
  const response = await fetch(url, { ...init, headers: { ...(await headers()), ...init.headers } });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Op?ration impossible");
  return result;
}
const formatDate = (value?:string|null) => value ? new Intl.DateTimeFormat("fr-FR", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)) : "Jamais";
const euro = new Intl.NumberFormat("fr-FR", { style:"currency", currency:"EUR" });

export function Administration({ requests, onGiftSaved, onRequestStatus }:{ requests:TransferRequest[]; onGiftSaved:(record:GiftRecord)=>void; onRequestStatus:(id:string,status:TransferRequest["status"])=>void }) {
  const [tab,setTab] = useState<Tab>("gifts");
  const tabs:{id:Tab;label:string;icon:string}[] = [
    {id:"gifts",label:"Cadeaux BTC",icon:"₿"},{id:"members",label:"Membres & accès",icon:"◎"},
    {id:"accounts",label:"Comptes & positions",icon:"▥"},{id:"settings",label:"Réglages admin",icon:"⚙"}
  ];
  return <div className="admin-root">
    <section className="admin-command"><div><span>ZONE PRIVÉE · FLORENT UNIQUEMENT</span><h2>Administration familiale</h2><p>Gérer les accès, les comptes et les données financières sans stocker de mot de passe, clé privée ou phrase Ledger.</p></div><b>Administrateur vérifié</b></section>
    <nav className="admin-tabs">{tabs.map(item=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav>
    {tab==="gifts"&&<BackOffice requests={requests} onGiftSaved={onGiftSaved} onRequestStatus={onRequestStatus} />}
    {tab==="members"&&<Members />}
    {tab==="accounts"&&<Accounts />}
    {tab==="settings"&&<Settings />}
  </div>;
}

function Members() {
  const [users,setUsers]=useState<Member[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  const [draft,setDraft]=useState({name:"",email:"",role:"child",birthdayDay:"",birthdayMonth:""});
  const load=useCallback(async()=>setUsers((await api("/api/admin/users")).users||[]),[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(e=>setMessage(e.message));},0);return()=>window.clearTimeout(timer);},[load]);
  async function create(event:FormEvent){event.preventDefault();setBusy("create");try{const result=await api("/api/admin/users",{method:"POST",body:JSON.stringify({...draft,birthdayDay:Number(draft.birthdayDay)||undefined,birthdayMonth:Number(draft.birthdayMonth)||undefined,sendInvite:true,redirectTo:window.location.origin})});setMessage(result.invitation?.sent?"Membre ajouté et invitation envoyée.":"Membre ajouté, mais e-mail non envoyé : "+(result.invitation?.reason||"à vérifier"));setDraft({name:"",email:"",role:"child",birthdayDay:"",birthdayMonth:""});setOpen(false);await load();}catch(e){setMessage(e instanceof Error?e.message:"Ajout impossible");}finally{setBusy("");}}
  async function action(user:Member,type:"invite"|"reset"|"toggle"|"delete"){if(type==="delete"&&!window.confirm("Supprimer "+user.name+" et ses données associées ?"))return;setBusy(user.id+type);try{if(type==="invite"||type==="reset"){const r=await api("/api/admin/users/actions",{method:"POST",body:JSON.stringify({action:type==="reset"?"reset_password":"invite",memberId:user.id,redirectTo:window.location.origin})});setMessage(r.message);}else if(type==="toggle"){await api("/api/admin/users",{method:"PATCH",body:JSON.stringify({id:user.id,isActive:!user.is_active})});setMessage(user.is_active?"Accès suspendu.":"Accès réactivé.");}else{await api("/api/admin/users?id="+encodeURIComponent(user.id),{method:"DELETE"});setMessage("Membre supprimé.");}await load();}catch(e){setMessage(e instanceof Error?e.message:"Action impossible");}finally{setBusy("");}}
  return <div className="admin-section">
    <div className="admin-summary"><Summary label="Membres autorisés" value={String(users.length)} note={users.filter(u=>u.is_active).length+" accès actifs"}/><Summary label="Comptes créés" value={String(users.filter(u=>u.auth_user_id).length)} note="Authentification Supabase"/><Summary label="Administrateurs" value="1" note="Florent uniquement"/></div>
    <section className="panel admin-panel-new"><header><div><span>AUTHENTIFICATION SUPABASE</span><h2>Membres & détails de connexion</h2><p>Les mots de passe restent chiffrés chez Supabase et ne sont jamais visibles.</p></div><button onClick={()=>setOpen(!open)}>＋ Ajouter un membre</button></header>
      {open&&<form className="admin-form member-form" onSubmit={create}><Field label="Nom"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="E-mail"><input required type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></Field><Field label="Rôle"><select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="child">Jeune investisseur</option><option value="adult">Adulte</option><option value="viewer">Lecture seule</option></select></Field><Field label="Jour"><input type="number" min="1" max="31" value={draft.birthdayDay} onChange={e=>setDraft({...draft,birthdayDay:e.target.value})}/></Field><Field label="Mois"><input type="number" min="1" max="12" value={draft.birthdayMonth} onChange={e=>setDraft({...draft,birthdayMonth:e.target.value})}/></Field><button disabled={busy==="create"}>{busy==="create"?"Envoi…":"Ajouter & inviter"}</button></form>}
      {message&&<p className="admin-feedback">{message}</p>}
      <div className="member-table"><div className="table-head"><span>Membre</span><span>Connexion</span><span>Dernière activité</span><span>Actions</span></div>{users.map(user=><article key={user.id} className={user.is_active?"":"disabled"}><div className="identity"><b>{user.name.slice(0,2).toUpperCase()}</b><span><strong>{user.name}</strong><small>{user.email||"E-mail manquant"} · {user.role}</small></span></div><div><Status ok={Boolean(user.auth_user_id&&user.auth?.emailConfirmedAt)}>{user.auth_user_id?(user.auth?.emailConfirmedAt?"Compte confirmé":"E-mail à confirmer"):"Jamais connecté"}</Status><small className="sub">{user.auth?.providers?.join(", ")||"E-mail"}</small></div><div><strong className="date">{formatDate(user.auth?.lastSignInAt)}</strong><small className="sub">Créé : {formatDate(user.auth?.createdAt)}</small></div><div className="actions">{!user.auth_user_id&&<button disabled={busy.startsWith(user.id)} onClick={()=>void action(user,"invite")}>Renvoyer invitation</button>}{user.auth_user_id&&<button disabled={busy.startsWith(user.id)} onClick={()=>void action(user,"reset")}>Réinitialiser mot de passe</button>}{user.role!=="admin"&&<><button className="quiet" onClick={()=>void action(user,"toggle")}>{user.is_active?"Suspendre":"Réactiver"}</button><button className="danger" onClick={()=>void action(user,"delete")}>Supprimer</button></>}</div></article>)}</div>
    </section>
  </div>;
}

function Accounts(){
  const [members,setMembers]=useState<Member[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[holdings,setHoldings]=useState<Holding[]>([]),[message,setMessage]=useState("");
  const [accountOpen,setAccountOpen]=useState(false),[holdingOpen,setHoldingOpen]=useState(false),[selected,setSelected]=useState("");
  const [a,setA]=useState({memberId:"",name:"",accountType:"pea",institution:"",currency:"EUR",accountNumberLast4:"",ibanLast4:"",walletAddress:"",network:"bitcoin-mainnet",notes:""});
  const [h,setH]=useState({assetType:"stock",symbol:"",isin:"",name:"",quantity:"",averageCost:"",currency:"EUR",exchange:"Euronext Paris",lastPrice:""});
  const [query,setQuery]=useState(""),[results,setResults]=useState<MarketResult[]>([]),[market,setMarket]=useState<boolean|null>(null);
  const load=useCallback(async()=>{const r=await Promise.all([api("/api/admin/users"),api("/api/admin/accounts")]);setMembers(r[0].users||[]);setAccounts(r[1].accounts||[]);setHoldings(r[1].holdings||[]);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(e=>setMessage(e.message));},0);return()=>window.clearTimeout(timer);},[load]);
  async function addAccount(e:FormEvent){e.preventDefault();try{await api("/api/admin/accounts",{method:"POST",body:JSON.stringify(a)});setMessage("Compte ajouté.");setAccountOpen(false);await load();}catch(x){setMessage(x instanceof Error?x.message:"Ajout impossible");}}
  async function importLedgers(){try{const r=await api("/api/admin/accounts",{method:"POST",body:JSON.stringify({importExistingWallets:true})});setMessage(r.message);await load();}catch(x){setMessage(x instanceof Error?x.message:"Import impossible");}}
  async function addHolding(e:FormEvent){e.preventDefault();try{await api("/api/admin/holdings",{method:"POST",body:JSON.stringify({...h,accountId:selected,quantity:Number(h.quantity),averageCost:h.averageCost?Number(h.averageCost):undefined,lastPrice:h.lastPrice?Number(h.lastPrice):undefined})});setMessage("Position ajoutée.");setHoldingOpen(false);await load();}catch(x){setMessage(x instanceof Error?x.message:"Ajout impossible");}}
  async function search(){try{const r=await api("/api/admin/market?q="+encodeURIComponent(query));setMarket(r.configured);setResults(r.results||[]);if(!r.configured)setMessage("Ajoutez ALPHA_VANTAGE_API_KEY dans Vercel. La saisie manuelle reste disponible.");}catch(x){setMessage(x instanceof Error?x.message:"Recherche indisponible");}}
  function choose(r:MarketResult){setH({...h,symbol:r.symbol,name:r.name,currency:r.currency||"EUR",exchange:r.region||"Euronext Paris",assetType:r.type.toLowerCase().includes("etf")?"etf":"stock"});setResults([]);}
  async function price(item:Holding){try{const r=await api("/api/admin/market?symbol="+encodeURIComponent(item.symbol||""));if(!r.quote?.price)throw new Error("Aucun cours disponible.");await api("/api/admin/holdings",{method:"PATCH",body:JSON.stringify({id:item.id,lastPrice:r.quote.price})});setMessage("Cours actualisé au "+(r.quote.asOf||"dernier jour de marché")+".");await load();}catch(x){setMessage(x instanceof Error?x.message:"Cours indisponible");}}
  async function remove(kind:"accounts"|"holdings",id:string,label:string){if(!window.confirm("Supprimer "+label+" ?"))return;try{await api("/api/admin/"+kind+"?id="+encodeURIComponent(id),{method:"DELETE"});setMessage("Élément supprimé.");await load();}catch(x){setMessage(x instanceof Error?x.message:"Suppression impossible");}}
  const total=useMemo(()=>holdings.reduce((s,x)=>s+Number(x.quantity)*Number(x.last_price||x.average_cost||0),0),[holdings]);
  return <div className="admin-section"><div className="admin-summary"><Summary label="Comptes financiers" value={String(accounts.length)} note="BTC, banque, PEA, CTO"/><Summary label="Positions" value={String(holdings.length)} note="Actions, ETF et autres"/><Summary label="Valeur documentée" value={euro.format(total)} note="Dernier cours connu"/></div>
    <section className="panel admin-panel-new"><header><div><span>PATRIMOINE MULTI-COMPTES</span><h2>Comptes & positions</h2><p>Ne saisissez que les 4 derniers caractères d&apos;un compte bancaire. Jamais d&apos;identifiant ou de clé privée.</p></div><div className="header-actions"><button onClick={()=>setAccountOpen(!accountOpen)}>＋ Ajouter un compte</button><button className="secondary" onClick={()=>void importLedgers()}>Importer les Ledger</button><button className="secondary" disabled={!accounts.length} onClick={()=>{setHoldingOpen(!holdingOpen);if(!selected&&accounts[0])setSelected(accounts[0].id);}}>＋ Ajouter une position</button></div></header>
      {message&&<p className="admin-feedback">{message}</p>}
      {accountOpen&&<form className="admin-form" onSubmit={addAccount}><Field label="Propriétaire"><select required value={a.memberId} onChange={e=>setA({...a,memberId:e.target.value})}><option value="">Choisir…</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Type"><select value={a.accountType} onChange={e=>setA({...a,accountType:e.target.value})}><option value="pea">PEA</option><option value="securities">Compte-titres</option><option value="bitcoin">Portefeuille BTC</option><option value="crypto_exchange">Plateforme crypto</option><option value="bank">Compte bancaire</option><option value="savings">Épargne</option><option value="other">Autre</option></select></Field><Field label="Nom du compte"><input required value={a.name} onChange={e=>setA({...a,name:e.target.value})}/></Field><Field label="Établissement"><input value={a.institution} onChange={e=>setA({...a,institution:e.target.value})}/></Field><Field label="Devise"><input maxLength={3} value={a.currency} onChange={e=>setA({...a,currency:e.target.value})}/></Field>{a.accountType==="bitcoin"||a.accountType==="crypto_exchange"?<><Field label="Adresse publique"><input value={a.walletAddress} onChange={e=>setA({...a,walletAddress:e.target.value})}/></Field><Field label="Réseau"><input value={a.network} onChange={e=>setA({...a,network:e.target.value})}/></Field></>:<><Field label="4 derniers chiffres"><input maxLength={4} value={a.accountNumberLast4} onChange={e=>setA({...a,accountNumberLast4:e.target.value})}/></Field><Field label="4 derniers caractères IBAN"><input maxLength={4} value={a.ibanLast4} onChange={e=>setA({...a,ibanLast4:e.target.value})}/></Field></>}<button>Enregistrer</button></form>}
      {holdingOpen&&<form className="holding-form" onSubmit={addHolding}><div className="asset-search"><Field label="Rechercher une action ou un ETF français"><div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom ou symbole"/><button type="button" onClick={()=>void search()}>Rechercher</button></div></Field>{results.length>0&&<div className="results">{results.map(r=><button type="button" key={r.symbol} onClick={()=>choose(r)}><strong>{r.name}</strong><small>{r.symbol} · {r.region} · {r.currency}</small></button>)}</div>}</div><p className="market-note">{market===false?"Recherche non configurée — saisie manuelle ci-dessous.":"Cours de clôture gratuits, adaptés au suivi mensuel d&apos;un PEA."}</p><div className="admin-form"><Field label="Compte"><select required value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Type"><select value={h.assetType} onChange={e=>setH({...h,assetType:e.target.value})}><option value="stock">Action</option><option value="etf">ETF</option><option value="fund">Fonds</option><option value="bond">Obligation</option><option value="cash">Liquidités</option><option value="crypto">Crypto</option><option value="other">Autre</option></select></Field><Field label="Nom"><input required value={h.name} onChange={e=>setH({...h,name:e.target.value})}/></Field><Field label="Symbole"><input value={h.symbol} onChange={e=>setH({...h,symbol:e.target.value})}/></Field><Field label="ISIN"><input value={h.isin} onChange={e=>setH({...h,isin:e.target.value})}/></Field><Field label="Place de cotation"><input value={h.exchange} onChange={e=>setH({...h,exchange:e.target.value})}/></Field><Field label="Quantité"><input required type="number" min="0" step="any" value={h.quantity} onChange={e=>setH({...h,quantity:e.target.value})}/></Field><Field label="Prix moyen unitaire"><input type="number" min="0" step="any" value={h.averageCost} onChange={e=>setH({...h,averageCost:e.target.value})}/></Field><Field label="Dernier cours"><input type="number" min="0" step="any" value={h.lastPrice} onChange={e=>setH({...h,lastPrice:e.target.value})}/></Field><Field label="Devise"><input maxLength={3} value={h.currency} onChange={e=>setH({...h,currency:e.target.value})}/></Field><button>Enregistrer</button></div></form>}
      <div className="account-list">{accounts.length===0?<div className="empty"><strong>Aucun compte</strong><p>Ajoutez un Ledger, un PEA, un compte-titres ou un compte bancaire.</p></div>:accounts.map(account=>{const owner=members.find(m=>m.id===account.member_id),positions=holdings.filter(x=>x.account_id===account.id);return <article className="account-card" key={account.id}><header><div className="account-icon">{account.account_type.includes("bitcoin")||account.account_type.includes("crypto")?"₿":account.account_type==="pea"?"P":"€"}</div><div><span>{owner?.name||"Membre"} · {account.account_type.toUpperCase()}</span><h3>{account.name}</h3><p>{account.institution||account.network||"Établissement non renseigné"} · {account.currency}{account.account_number_last4?" · •••• "+account.account_number_last4:""}</p></div><button className="danger-link" onClick={()=>void remove("accounts",account.id,account.name)}>Supprimer</button></header>{account.wallet_address&&<p className="wallet">{account.wallet_address}</p>}<div className="positions">{positions.length===0?<p className="empty">Aucune position.</p>:positions.map(item=><div key={item.id}><b className="asset">{item.asset_type==="etf"?"ETF":item.asset_type==="stock"?"ACT":"AUT"}</b><span><strong>{item.name}</strong><small>{item.symbol||"Sans symbole"}{item.isin?" · "+item.isin:""}</small></span><span><strong>{Number(item.quantity).toLocaleString("fr-FR")} unités</strong><small>PRU {Number(item.average_cost||0).toLocaleString("fr-FR")} {item.currency}</small></span><span><strong>{Number(item.last_price||0).toLocaleString("fr-FR")} {item.currency}</strong><small>{item.last_price_at?formatDate(item.last_price_at):"Cours manuel"}</small></span><span className="position-actions">{item.symbol&&<button onClick={()=>void price(item)}>Actualiser</button>}<button onClick={()=>void remove("holdings",item.id,item.name)}>×</button></span></div>)}</div></article>;})}</div>
    </section>
  </div>;
}

function Settings(){
  const [db,setDb]=useState<{connected?:boolean;projectUrl?:string}|null>(null),[market,setMarket]=useState<{configured?:boolean;provider?:string}|null>(null);
  useEffect(()=>{void fetch("/api/supabase/status").then(r=>r.json()).then(setDb);void api("/api/admin/market").then(setMarket).catch(()=>setMarket({configured:false,provider:"Alpha Vantage"}));},[]);
  return <section className="panel admin-panel-new settings-admin"><header><div><span>CONFIGURATION SERVEUR</span><h2>Réglages administrateur</h2><p>Les clés secrètes restent dans Vercel et ne sont jamais envoyées au navigateur.</p></div></header><div className="services"><Service ok={Boolean(db?.connected)} title="Base Supabase" value={db?.projectUrl||"À configurer"} note="Membres, comptes, positions et cadeaux."/><Service ok={Boolean(market?.configured)} title="Données de marché" value={market?.provider||"Alpha Vantage"} note="Actions et ETF mondiaux · cours de clôture · 25 requêtes/jour."/><Service ok title="Administrateur" value="florent.lambert@gmail.com" note="Contrôle côté serveur sur toutes les routes."/></div>{!market?.configured&&<div className="setup"><b>Activer les cours actions / ETF</b><p>Ajoutez <code>ALPHA_VANTAGE_API_KEY</code> dans Vercel → Project Settings → Environment Variables, puis redéployez.</p><a href="https://www.alphavantage.co/support/#api-key" target="_blank" rel="noreferrer">Créer une clé gratuite ↗</a></div>}<div className="rules"><h3>Règles de sécurité</h3><ul><li>Jamais de 24 mots Ledger, clé privée, code PIN ou identifiant bancaire.</li><li>Seulement les 4 derniers caractères des comptes bancaires.</li><li>Les réinitialisations sont envoyées directement par Supabase.</li><li>Les cours sont informatifs et ne constituent pas un conseil financier.</li></ul></div></section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label>{label}{children}</label>}
function Summary({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Status({ok,children}:{ok:boolean;children:React.ReactNode}){return <span className={"admin-status "+(ok?"ok":"pending")}><i/>{children}</span>}
function Service({ok,title,value,note}:{ok:boolean;title:string;value:string;note:string}){return <article><Status ok={ok}>{ok?"Connect?":"Optionnel"}</Status><h3>{title}</h3><p>{value}</p><small>{note}</small></article>}
